// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcPHknyBJGygj6JdJ1dv7E9Sy8fjW_uNQ',
    appId: '1:957255439034:web:73ad9bf919a1ff7df2e883',
    messagingSenderId: '957255439034',
    projectId: 'kutuphane-otomasyonu-9a769',
    authDomain: 'kutuphane-otomasyonu-9a769.firebaseapp.com',
    storageBucket: 'kutuphane-otomasyonu-9a769.appspot.com',
    measurementId: 'G-951CEYWEQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwz46XJZvkRxNE6f3SFaInjvIAOzLbwRU',
    appId: '1:957255439034:android:ad69ebeefd1dea30f2e883',
    messagingSenderId: '957255439034',
    projectId: 'kutuphane-otomasyonu-9a769',
    storageBucket: 'kutuphane-otomasyonu-9a769.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrWau-9DZWePS96AOXHZafnNxgmZqkS6w',
    appId: '1:957255439034:ios:e7b5d44915298d5ff2e883',
    messagingSenderId: '957255439034',
    projectId: 'kutuphane-otomasyonu-9a769',
    storageBucket: 'kutuphane-otomasyonu-9a769.appspot.com',
    iosBundleId: 'com.example.kutuphaneOtomasyonu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrWau-9DZWePS96AOXHZafnNxgmZqkS6w',
    appId: '1:957255439034:ios:544fea2f46af26dff2e883',
    messagingSenderId: '957255439034',
    projectId: 'kutuphane-otomasyonu-9a769',
    storageBucket: 'kutuphane-otomasyonu-9a769.appspot.com',
    iosBundleId: 'com.example.kutuphaneOtomasyonu.RunnerTests',
  );
}
