// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaqk36HZrFW0thvD37CuTgFOVng-HUz9g',
    appId: '1:765929737430:web:426c466d1c2f97825b0d77',
    messagingSenderId: '765929737430',
    projectId: 'final-21b56',
    authDomain: 'final-21b56.firebaseapp.com',
    storageBucket: 'final-21b56.appspot.com',
    measurementId: 'G-M6ZBYFP7MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgD_FBJ8MRXPqyp4taAS_Fik-z7PkhYRI',
    appId: '1:765929737430:android:d7aec7613443f4f15b0d77',
    messagingSenderId: '765929737430',
    projectId: 'final-21b56',
    storageBucket: 'final-21b56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGtZwbIJ8UKbnIg9K0CpzfWoWjl4yrDg8',
    appId: '1:765929737430:ios:650b338bc5581ee75b0d77',
    messagingSenderId: '765929737430',
    projectId: 'final-21b56',
    storageBucket: 'final-21b56.appspot.com',
    iosBundleId: 'com.example.finalpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGtZwbIJ8UKbnIg9K0CpzfWoWjl4yrDg8',
    appId: '1:765929737430:ios:5d6507a7786262225b0d77',
    messagingSenderId: '765929737430',
    projectId: 'final-21b56',
    storageBucket: 'final-21b56.appspot.com',
    iosBundleId: 'com.example.finalpro.RunnerTests',
  );
}
